# This file was generated by GoReleaser. DO NOT EDIT.
cask "warmbox" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "75185b3558bee096e2770c42ea00eb10ac93899b9916b8d35c0909235ddf7c83"
      url "https://github.com/Daviduche03/warmbox/releases/download/v#{version}/warmbox_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5a220ecf1bfe208a35abd3a51550235e976c60b104558854c2fde5f715aef0be"
      url "https://github.com/Daviduche03/warmbox/releases/download/v#{version}/warmbox_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bdf620b4610b7dca28c2443a2c9d8765c7f31e70f55c014d5d03c1bafbbf9358"
      url "https://github.com/Daviduche03/warmbox/releases/download/v#{version}/warmbox_#{version}_linux_amd64.tar.gz"
    end
  end

  name "warmbox"
  desc "Self-hosted GUI desktop microVMs (vfkit/QEMU + noVNC)"
  homepage "https://github.com/Daviduche03/warmbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "warmbox"

  # No zap stanza required

  caveats <<~EOS
    Warmbox needs a hypervisor:
      macOS:  brew install vfkit
      Linux:  QEMU + KVM (qemu-system-x86_64 / qemu-system-aarch64)

    Then fetch the guest image and start the daemon:
      warmbox setup
      warmbox service install --pool 1

    The dashboard is on http://localhost:7070
  EOS
end
