# This file was generated by GoReleaser. DO NOT EDIT.
cask "warmbox" do
  version "0.5.1"

  on_macos do
    on_arm do
      sha256 "dec00199039b21cf3eed442fdc05981e651f3fdb4d681452a42ca874091c1d6a"
      url "https://github.com/Daviduche03/warmbox/releases/download/v#{version}/warmbox_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5125d2c507f94751285a40009d70ad7dd6f0f0348bbe2884250677e24988a956"
      url "https://github.com/Daviduche03/warmbox/releases/download/v#{version}/warmbox_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "39b798dcff61689a7c66de42579cd2fd81372f8b90970b58673fec86c937e90a"
      url "https://github.com/Daviduche03/warmbox/releases/download/v#{version}/warmbox_#{version}_linux_amd64.tar.gz"
    end
  end

  name "warmbox"
  desc "Self-hosted GUI desktop microVMs (vfkit/QEMU + noVNC)"
  homepage "https://github.com/Daviduche03/warmbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "warmbox"

  # No zap stanza required

  caveats <<~EOS
    Warmbox needs a hypervisor:
      macOS:  brew install vfkit
      Linux:  QEMU + KVM (qemu-system-x86_64 / qemu-system-aarch64)

    Then fetch the guest image and start the daemon:
      warmbox setup
      warmbox service install --pool 1

    The dashboard is on http://localhost:7070
  EOS
end
