# This file was generated by GoReleaser. DO NOT EDIT.
cask "warmbox" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "bcc70cf7dc729a0f818126b20c8a241240530a25e1a2fb5a134bd3f64400008a"
      url "https://github.com/Daviduche03/warmbox/releases/download/v#{version}/warmbox_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a339a6ceaeab14589c74089b6efc1479d51dd79352e4f3dd939688040e0c2d7d"
      url "https://github.com/Daviduche03/warmbox/releases/download/v#{version}/warmbox_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4f20796fa93fc87f4ffb37dd8bc3e3b2c4044d2a1e332b2e25c19df43e5c63ff"
      url "https://github.com/Daviduche03/warmbox/releases/download/v#{version}/warmbox_#{version}_linux_amd64.tar.gz"
    end
  end

  name "warmbox"
  desc "Self-hosted GUI desktop microVMs (vfkit/QEMU + noVNC)"
  homepage "https://github.com/Daviduche03/warmbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "warmbox"

  # No zap stanza required

  caveats <<~EOS
    Warmbox needs a hypervisor:
      macOS:  brew install vfkit
      Linux:  QEMU + KVM (qemu-system-x86_64 / qemu-system-aarch64)

    Then fetch the guest image and start the daemon:
      warmbox setup
      warmbox service install --pool 1

    The dashboard is on http://localhost:7070
  EOS
end
